name: _build

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      build-cache-key:
        description: 'Cache key for build output'
        value: ${{ jobs.build.outputs.build-cache-key }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-cache-key: ${{ steps.cache-build-output.outputs.cache-hit }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Restore node_modules cache
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Extract Version
        id: version
        run: |
          VERSION=$(grep version package.json | sed 's/.*"version": "\(.*\)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup build output cache
        id: cache-build-output
        uses: actions/cache@v5
        with:
          path: dist
          key: ${{ runner.os }}-build-output-${{ hashFiles('**/package-lock.json', '**/src/**', '**/package.json') }}-${{ steps.version.outputs.version }}

      - name: Build
        run: npm run build
        if: steps.cache-build-output.outputs.cache-hit != 'true'
